persistence:
  advancedVisibilityStore: pinot-visibility
  datastores:
    pinot-visibility:
      pinot:
        broker: "localhost:8099"
        cluster: pinot-test
        table: "cadence_visibility_pinot"
    es-visibility:
      elasticsearch:
        version: "v6"
        url:
          scheme: "http"
          host: "127.0.0.1:9200"
        indices:
          visibility: cadence-visibility-dev

kafka:
  tls:
    enabled: false
  clusters:
    test:
      brokers:
        - 127.0.0.1:9092
  topics:
    cadence-visibility-dev:
      cluster: test
    cadence-visibility-dev-dlq:
      cluster: test
    cadence-visibility-pinot:
      cluster: test
    cadence-visibility-pinot-dlq:
      cluster: test
  applications:
    visibility:
      topic: cadence-visibility-dev
      dlq-topic: cadence-visibility-dev-dlq
    pinot-visibility:
      topic: cadence-visibility-pinot
      dlq-topic: cadence-visibility-pinot-dlq

dynamicconfig:
  client: filebased
  filebased:
    filepath: "config/dynamicconfig/development_pinot.yaml"